Repository OpenVoiceOS/ovos-bus-client, pull requests merged in 2023-12, with the labels that each got.

#65 Update to stable dependency specs
  requirements.txt
Labels: packaging

#66 feat/bus_apis
  ovos_bus_client/apis/__init__.py
  ovos_bus_client/apis/enclosure.py
  ovos_bus_client/apis/ocp.py
  ovos_bus_client/client/client.py
  setup.py
Labels: refactor, packaging

#67 feat/gui_bus_api
  ovos_bus_client/apis/gui.py
Labels: refactor, packaging

#68 refactor/bus_utils
  ovos_bus_client/apis/gui.py
  ovos_bus_client/apis/ocp.py
  ovos_bus_client/client/client.py
  ovos_bus_client/message.py
  ovos_bus_client/util/__init__.py
  ovos_bus_client/util/scheduler.py
  requirements.txt
  test/unittests/test_client.py
Labels: refactor, packaging

#71 fix/get_message_lang
  ovos_bus_client/util/__init__.py
  test/unittests/test_message.py
Labels: bug

#73 fix/log spam
  ovos_bus_client/apis/gui.py
Labels: bug
