Repository OpenVoiceOS/ovos-bus-client, pull requests merged in 2024-01, with the labels that each got.

#74 fix/ocp api
  ovos_bus_client/apis/ocp.py
  requirements.txt
Labels: bug, enhancement

#77 fix/ocp api
  ovos_bus_client/apis/ocp.py
Labels: bug

#76 hotfix/avoid_c++_crash
  ovos_bus_client/scripts.py
Labels: bug

#78 feat/ovos-media
  .github/workflows/publish_alpha.yml
  .github/workflows/unit_tests.yml
  ovos_bus_client/apis/ocp.py
  requirements.txt
Labels: enhancement

#79 typo_and_docstr
  ovos_bus_client/apis/ocp.py
Labels: bug

#75 refactor/orjson
  ovos_bus_client/client/client.py
  ovos_bus_client/message.py
  ovos_bus_client/util/__init__.py
  requirements.txt
Labels: refactor

#81 fix/info_leak
  ovos_bus_client/session.py
Labels: bug

#83 Update default values
  ovos_bus_client/session.py
Labels: bug
