Repository OpenVoiceOS/ovos-bus-client, pull requests merged in 2024-06, with the labels that each got.

#98 feat/blacklist_from_session
  ovos_bus_client/session.py
Labels: enhancement

#97 refactor/handle_new_SEIs
  ovos_bus_client/apis/ocp.py
  requirements.txt
Labels: refactor

#100 hotfix/StreamPlugin
  ovos_bus_client/apis/ocp.py
Labels: bug

#96 Update error handling to reduce unhandled exceptions
  ovos_bus_client/client/client.py
Labels: bug
