Repository OpenVoiceOS/ovos-bus-client, pull requests merged in 2024-05, with the labels that each got.

#93 feat/track_speaking+recording_per_session
  ovos_bus_client/session.py
Labels: enhancement

#94 Update imports to support ovos-utils~=0.0.x with compat. warnings
  ovos_bus_client/apis/ocp.py
  requirements.txt
Labels: packaging

#95 Update setup.py to resolve version automation bug
  setup.py
Labels: bug, packaging
