Repository OpenVoiceOS/ovos-bus-client, pull requests merged in 2024-11, with the labels that each got.

#120 refactor!:deprecate QML upload from bus
  ovos_bus_client/apis/gui.py
Labels: breaking

#136 fix: resolve image urls
  ovos_bus_client/apis/gui.py
Labels: fix

#138 fix: image urls
  ovos_bus_client/apis/gui.py
Labels: fix

#141 fix: remove dead code
  ovos_bus_client/client/client.py
  ovos_bus_client/client/collector.py
  ovos_bus_client/client/waiter.py
  ovos_bus_client/message.py
  ovos_bus_client/util/__init__.py
  ovos_bus_client/util/scheduler.py
  ovos_bus_client/util/utils.py
  test/requirements.txt
  test/unittests/test_client.py
  test/unittests/test_compat.py
  test/unittests/test_event_scheduler.py
  test/unittests/test_message.py
  test/unittests/test_util.py
Labels: fix

#140 chore: fix pyee import, maintain backwards compat
  .github/workflows/unit_tests.yml
  ovos_bus_client/client/client.py
  requirements.txt
  test/unittests/test_client.py
  test/unittests/test_event_scheduler.py
Labels: ignore-for-release

#143 chore: Update README.md
  README.md
Labels: ignore-for-release
